name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    name: Test crate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@stable
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - run: cargo test --all-features
        name: Test with coverage

  lint:
    name: Check code style

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@master
        name: Set up toolchain
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - uses: actions-rs/cargo@v1
        name: Check code with cargo fmt
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: Check code with cargo clippy
        with:
          command: clippy
          args: --all-targets -- -D warnings
